#!/usr/bin/env python3
"""RV Market Intelligence — CLI report generator.

Usage:
    python report.py                          # default watchlist (India + US)
    python report.py RELIANCE.NS AAPL TSLA    # custom symbols
    python report.py --ai                     # include AI analysis (needs GROQ_API_KEY in .env)
    python report.py --focus "IT sector"      # give the AI team a focus
    python report.py --out my-report.md       # custom output file

Output: reports/<file>.md
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent))
from core import agents, data  # noqa: E402

DEFAULT_WATCHLIST = [
    "^NSEI", "^NSEBANK", "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS",
    "ICICIBANK.NS", "INFY.NS", "TATAMOTORS.NS",
    "^GSPC", "^IXIC", "AAPL", "MSFT", "NVDA", "TSLA",
]


def main() -> int:
    ap = argparse.ArgumentParser(description="RV Market Intelligence report")
    ap.add_argument("symbols", nargs="*", help="symbols (default: India+US watchlist)")
    ap.add_argument("--ai", action="store_true", help="include AI team analysis")
    ap.add_argument("--focus", default="", help="focus instruction for the AI team")
    ap.add_argument("--out", default="", help="output .md file path")
    args = ap.parse_args()

    load_dotenv(Path(__file__).parent / ".env")
    symbols = [s.upper() if not s.startswith("^") and "." not in s else s
               for s in (args.symbols or DEFAULT_WATCHLIST)]

    print(f"📡 Fetching data for {len(symbols)} symbols …")
    bundle = data.get_quotes(symbols)
    mode = bundle["mode"]
    print(f"   data mode: {mode.upper()}")
    for q in sorted(bundle["quotes"], key=lambda x: x["change_pct"], reverse=True):
        t = q["technicals"]
        print(f"   {q['symbol']:<14} {q['price']:>12,.2f} {q['change_pct']:>+7.2f}%  "
              f"RSI {t['rsi14']!s:>5}  {t['signal']}")

    md = [f"# RV Market Intelligence Report",
          f"*Generated {datetime.now():%d %b %Y, %H:%M} — data: {mode.upper()}*",
          "", "| Symbol | Name | Price | Day % | RSI | Signal |",
          "|---|---|---|---|---|---|"]
    for q in sorted(bundle["quotes"], key=lambda x: x["change_pct"], reverse=True):
        t = q["technicals"]
        md.append(f"| {q['symbol']} | {q['name']} | {q['price']:,} {q['currency']} | "
                  f"{q['change_pct']:+.2f}% | {t['rsi14']} | {t['signal']} |")

    md += ["", "## Technical Detail", ""]
    for q in bundle["quotes"]:
        t = q["technicals"]
        md += [f"### {q['symbol']} — {q['name']} ({t['signal']})",
               f"- Price {q['price']:,} ({q['change_pct']:+.2f}%), RSI {t['rsi14']}, "
               f"52w position {t['pos_52w']}%"]
        md += [f"- {r}" for r in t["reasons"]] + [""]

    if args.ai:
        key = os.getenv("GROQ_API_KEY") or os.getenv("XAI_API_KEY")
        if not key:
            print("\n⚠️  --ai diya hai par API key nahi mili. .env me GROQ_API_KEY set karo "
                  "(free key: https://console.groq.com/keys)")
        else:
            base = "https://api.groq.com/openai/v1" if os.getenv("GROQ_API_KEY") \
                else "https://api.x.ai/v1"
            model = os.getenv("GROQ_MODEL") or os.getenv("XAI_MODEL")
            print("\n🤖 AI team chal rahi hai (5 agents) …")
            try:
                result = agents.run_team(bundle["quotes"], symbols,
                                         agents.LLM(key, base, model),
                                         focus=args.focus)
                md += ["## AI Intelligence Team Report", "", result["final"], ""]
                print("   ✅ AI report ready")
            except agents.LLMError as e:
                print(f"   ❌ AI failed: {e}")
                md += [f"_AI section failed: {e}_", ""]
    else:
        md += ["## AI Intelligence Team Report", "",
               "_`--ai` flag ke saath chalao (free key: console.groq.com/keys)_", ""]

    md += ["---", "_Auto-generated by RV Market Intelligence. Not investment advice._"]
    text = "\n".join(md)

    out_dir = Path(__file__).parent / "reports"
    out_dir.mkdir(exist_ok=True)
    out = Path(args.out) if args.out else out_dir / f"market-intel-{datetime.now():%Y%m%d-%H%M}.md"
    out.write_text(text, encoding="utf-8")
    print(f"\n📄 Report saved: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
